language: node_js
node_js:
- '0.10.33'
before_script:
- npm install
script:
- npm test
notifications:
  hipchat:
    rooms:
      secure: TH70IKa8gkW91MIIz2z+fuqXv54G4Rozjq5YxjoenRJRPPvHmpn3nf6RAoIRf4iFsqzL1ZsW+cFTvufT9jYT+ThdPRFH28qBJFGlfMR8rRSM8TfBrdoQvexXncQ25HijpJ5+cJYV0b9kfKEXYpeFXk+fztSqoVYU785rJO06klw=
